# Generated by Django 4.1.4 on 2023-01-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppIntermedia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emisor', models.CharField(max_length=1000)),
                ('Receptor', models.CharField(max_length=1000)),
                ('Cuerpo', models.CharField(max_length=1000)),
                ('Leido', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='banco',
            name='Provincia',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='banco',
            name='Sucursal',
            field=models.CharField(max_length=20),
        ),
    ]
