# Generated by Django 4.1.4 on 2023-01-24 03:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DM', '0003_canalcomun_canalmensaje_canalusuario_delete_mensaje_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CanalComun',
            new_name='Canal',
        ),
    ]
