# Generated by Django 4.1.4 on 2023-01-31 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DM', '0004_rename_canalcomun_canal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canal',
            name='actualizar',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='canalmensaje',
            name='actualizar',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='canalusuario',
            name='actualizar',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
